openapi: 3.0.1
info:
  title: LEAD ONE Python Runner API
  description: API for executing base64-encoded Python code and accessing runner status.
  version: "1.0.0"
servers:
  - url: https://c3p-python-runner.onrender.com

paths:
  /run:
    post:
      summary: Execute base64 Python code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: Base64-encoded Python code
      responses:
        '200':
          description: Execution result

  /status:
    get:
      summary: Get the last execution status
      responses:
        '200':
          description: Latest run result

  /log:
    get:
      summary: Retrieve recent execution logs
      responses:
        '200':
          description: List of past execution results

  /ping:
    get:
      summary: Uptime ping
      responses:
        '200':
          description: Server alive check
